# Generated by Django 4.0.10 on 2023-09-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeonato', models.CharField(max_length=60)),
                ('poblacion', models.CharField(max_length=12)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('puesto', models.CharField(max_length=6)),
                ('marca', models.DateTimeField(max_length=10)),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
            },
        ),
    ]
